#ifndef ERROR_CODE_H
#define ERROR_CODE_H

enum ErrorCode {
    UNKNOWN_ERROR = -100,
    SYS_SOCKET_ERROR,
    SYS_BIND_ERROR,
    SYS_LISTEN_ERROR,
    SYS_SEND_ERROR,
    SYS_RECV_ERROR,
    SYS_SELECT_ERROR,
    MISSING_ENV_VAR,
    INVALID_ADDRESS,
    WRONG_MESSAGE_TYPE,
    NO_REGISTERED_METHODS,
    BINDER_DIED,
    FUNCTION_NOT_REGISTERED,
    SKELETON_EXCEPTION,
    MSG_SEND_ERROR,
    MSG_RECV_ERROR
};

#endif